
services:
###> doctrine/doctrine-bundle ###
  db:
    image: mariadb:${MARIADB_VERSION:-10.6.18}
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"
    ###< doctrine/doctrine-bundle ###

  apache:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - database

###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
